apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/J0hn-B/keda_demo"
    path: k8s/argo-cd/charts/keda-demo
    targetRevision: main
    helm:
      valueFiles:
        - staging-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=background
