apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/J0hn-B/keda_demo.git"
    path: k8s/apps/keda-demo/consumer/
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
